# Site settings
title: XF Blog
SEOTitle: 游匠的世界博客 | XF Blog
header-img: img/background.png
email: xufengmike868@gmail.com
description: "there is only failure that you give up!"
keyword: "X-by-wire, UGV, STM32, MSP430, machine learn, Vehicle dynamics, 印象笔记, Apple, South Korea"
url: "http://youjiangworld.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/youjiangworld/youjiangworld.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "living a life what you want to be"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     游匠的世界
zhihu_username:     游匠的世界
github_username:    youjiangworld
facebook_username:  XU Feng




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 53cb2a368b13cac689c0                            #生成的clientID
  clientSecret: 8c93488b8328814c07646cbd4d1fcdb69554be35    #生成的clientSecret
  repo: youjiangworld .github.io    #仓库名称
  owner: youjiangworld    #github用户名
  admin: youjiangworld 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?3666c436a3149bcf33a089b3a8943d5f";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>


# Google Analytics
ga_track_id: 'UA-150342587-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


